### ISSUE TITLE
build fails on win32 with dmd

### ISSUE THREAD

**Issue by jnorwood** [DlangScience/examples#1]
I apologize if I just haven't found where the compiler restrictions are:
I pulled down
DMD32 D Compiler v2.069.2
DUB version 0.9.24, built on Sep 20 2015
    "dip80-ndslice": "~>0.8.4",
    "imageformats": "~>5.2.0"

Attempted build of the ndslice example fails.  
source code is:
https://github.com/DlangScience/examples/blob/master/image_processing/median-filter/source/app.d

Is this supposed to work only on 2.068 versions?
Thanks, Jay

====================  Starting D build  ====================
Cleared problem markers for nd1.
***********\*  Building D project: nd1  ************

> > Running: "C:\Program Files\dub\dub.exe" build
> > Performing "debug" build using dmd for x86.
> > dip80-ndslice 0.8.4: target for configuration "library" is up to date.
> > imageformats 5.2.0: target for configuration "library" is up to date.
> > nd1 ~master: building configuration "application"...
> > src\app.d(120,20): Error: template std.experimental.ndslice.slice.sliced cannot deduce function from argument types !()(ubyte[], long, long, ColFmt), candidates are:
> > C:\Users\rlxv10\AppData\Roaming\dub\packages\dip80-ndslice-0.8.4\source\std\experimental\ndslice\slice.d(39,6):        std.experimental.ndslice.slice.sliced(Flag mod = ReplaceArrayWithPointer.yes, Range, Lengths...)(Range range, Lengths lengths) if (!isStaticArray!Range && !isNarrowString!Range && allSatisfy!(isIndex, Lengths) && Lengths.length)
> > C:\Users\rlxv10\AppData\Roaming\dub\packages\dip80-ndslice-0.8.4\source\std\experimental\ndslice\slice.d(47,6):        std.experimental.ndslice.slice.sliced(Flag mod = ReplaceArrayWithPointer.yes, uint N, Range)(Range range, auto ref size_t[N] lengths, size_t shift = 0) if (!isStaticArray!Range && !isNarrowString!Range && N)
> > C:\Users\rlxv10\AppData\Roaming\dub\packages\dip80-ndslice-0.8.4\source\std\experimental\ndslice\slice.d(116,1):        std.experimental.ndslice.slice.sliced(Names...) if (Names.length && !anySatisfy!(isType, Names) && allSatisfy!(isStringValue, Names))
> > dmd failed with exit code 1.
> >   ^^^ Terminated, exit code: 2 ^^^
> > ***********\*  Build terminated.  ************

**Comment by 9il** [comment]
@jnorwood Thank you for the bug report! Does it works now for you with recent git commit?

**Comment by jnorwood** [comment]
Yes, thanks.  It builds without error now.
